# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 280)
        MainWindow.setMaximumSize(QtCore.QSize(480, 280))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/python.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.clear_url = QtWidgets.QPushButton(self.centralwidget)
        self.clear_url.setGeometry(QtCore.QRect(400, 40, 71, 31))
        self.clear_url.setObjectName("clear_url")
        self.process_url = QtWidgets.QPushButton(self.centralwidget)
        self.process_url.setGeometry(QtCore.QRect(14, 112, 451, 41))
        self.process_url.setObjectName("process_url")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(39, 160, 431, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.database_check_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.database_check_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.database_check_label.setObjectName("database_check_label")
        self.verticalLayout.addWidget(self.database_check_label)
        self.algorithm_check_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.algorithm_check_label.setText("")
        self.algorithm_check_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.algorithm_check_label.setObjectName("algorithm_check_label")
        self.verticalLayout.addWidget(self.algorithm_check_label)
        self.rating_check_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rating_check_label.setText("")
        self.rating_check_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rating_check_label.setObjectName("rating_check_label")
        self.verticalLayout.addWidget(self.rating_check_label)
        self.url_entry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.url_entry.setGeometry(QtCore.QRect(13, 10, 381, 91))
        self.url_entry.setObjectName("url_entry")
        self.database_check_result = QtWidgets.QLabel(self.centralwidget)
        self.database_check_result.setGeometry(QtCore.QRect(10, 158, 21, 21))
        self.database_check_result.setText("")
        self.database_check_result.setScaledContents(True)
        self.database_check_result.setObjectName("database_check_result")
        self.algorithm_check_result = QtWidgets.QLabel(self.centralwidget)
        self.algorithm_check_result.setGeometry(QtCore.QRect(10, 180, 21, 21))
        self.algorithm_check_result.setText("")
        self.algorithm_check_result.setScaledContents(True)
        self.algorithm_check_result.setObjectName("algorithm_check_result")
        self.rating_check_result = QtWidgets.QLabel(self.centralwidget)
        self.rating_check_result.setGeometry(QtCore.QRect(10, 200, 21, 21))
        self.rating_check_result.setText("")
        self.rating_check_result.setScaledContents(True)
        self.rating_check_result.setObjectName("rating_check_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Проверка сайтов на мошенничество"))
        self.clear_url.setText(_translate("MainWindow", "Очистить"))
        self.process_url.setText(_translate("MainWindow", "Начать проверку"))
        self.database_check_label.setText(_translate("MainWindow", "Программа готова к работе"))
        self.url_entry.setPlaceholderText(_translate("MainWindow", "Введите ссылку..."))
import qt.resources_rc
